set -g prefix C-a
set -g mouse on
set -g history-limit 25000

# status bar
set -g status-right ""
set -g status-left ""

set -g status-style "fg=#665c54"
set -g status-bg default

set -g status-justify left
set -g status-position bottom

# rename panes to current working directory
set -g status-interval 1
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'

# count the panes from 1
set -g base-index 1
setw -g pane-base-index 1

# reload configuration
bind-key -r r source-file ~/.tmux.conf

# https://github.com/alacritty/alacritty/issues/4576
set -g mode-style "fg=default,bg=default,reverse"
